[Settings]
ID = "ad7e0da9-56cf-4a1d-8873-ccfb3bd65251"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory to change to before starting a build.
  base    = "security/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "security/build/"
  # This will be your default build command
  command = "yarn build"